//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Center.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Education_Center.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23659846 {
            get {
                object obj = ResourceManager.GetObject("23659846", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2796195_200 {
            get {
                object obj = ResourceManager.GetObject("2796195-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Apluslogo {
            get {
                object obj = ResourceManager.GetObject("Apluslogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap belliconB {
            get {
                object obj = ResourceManager.GetObject("belliconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap belliconW {
            get {
                object obj = ResourceManager.GetObject("belliconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booksiconB {
            get {
                object obj = ResourceManager.GetObject("booksiconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap booksiconW {
            get {
                object obj = ResourceManager.GetObject("booksiconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap charticonB {
            get {
                object obj = ResourceManager.GetObject("charticonB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap charticonW {
            get {
                object obj = ResourceManager.GetObject("charticonW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeicon {
            get {
                object obj = ResourceManager.GetObject("closeicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employees_with_laptops_learning_professional_trainig_335657_3298 {
            get {
                object obj = ResourceManager.GetObject("employees-with-laptops-learning-professional-trainig_335657-3298", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employees_with_laptops_learning_professional_trainig_335657_32981 {
            get {
                object obj = ResourceManager.GetObject("employees-with-laptops-learning-professional-trainig_335657-32981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employees_with_laptops_learning_professional_trainig_335657_32982 {
            get {
                object obj = ResourceManager.GetObject("employees-with-laptops-learning-professional-trainig_335657-32982", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap erroricon {
            get {
                object obj = ResourceManager.GetObject("erroricon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exiticon {
            get {
                object obj = ResourceManager.GetObject("exiticon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exiticonB {
            get {
                object obj = ResourceManager.GetObject("exiticonB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exiticonW {
            get {
                object obj = ResourceManager.GetObject("exiticonW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female_teacher_explaining_lesson_students_179970_988 {
            get {
                object obj = ResourceManager.GetObject("female-teacher-explaining-lesson-students_179970-988", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fullscreeeniconB {
            get {
                object obj = ResourceManager.GetObject("fullscreeeniconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fullscreeeniconW {
            get {
                object obj = ResourceManager.GetObject("fullscreeeniconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap happy_diverse_students_celebrating_graduation_from_school_74855_5853 {
            get {
                object obj = ResourceManager.GetObject("happy-diverse-students-celebrating-graduation-from-school_74855-5853", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap happy_diverse_students_celebrating_graduation_from_school_74855_58531 {
            get {
                object obj = ResourceManager.GetObject("happy-diverse-students-celebrating-graduation-from-school_74855-58531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap happy_women_learning_language_online_isolated_flat_vector_illustration_cartoon_female_characters_taking_individual_lessons_through_messenger_education_digital_technology_concept_74855_10088 {
            get {
                object obj = ResourceManager.GetObject("happy-women-learning-language-online-isolated-flat-vector-illustration-cartoon-fe" +
                        "male-characters-taking-individual-lessons-through-messenger-education-digital-te" +
                        "chnology-concept_74855-10088", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap happy_women_learning_language_online_isolated_flat_vector_illustration_cartoon_female_characters_taking_individual_lessons_through_messenger_education_digital_technology_concept_74855_100881 {
            get {
                object obj = ResourceManager.GetObject("happy-women-learning-language-online-isolated-flat-vector-illustration-cartoon-fe" +
                        "male-characters-taking-individual-lessons-through-messenger-education-digital-te" +
                        "chnology-concept_74855-100881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap happy_women_learning_language_online_isolated_flat_vector_illustration_cartoon_female_characters_taking_individual_lessons_through_messenger_education_digital_technology_concept_74855_100882 {
            get {
                object obj = ResourceManager.GetObject("happy-women-learning-language-online-isolated-flat-vector-illustration-cartoon-fe" +
                        "male-characters-taking-individual-lessons-through-messenger-education-digital-te" +
                        "chnology-concept_74855-100882", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap happy_women_learning_language_online_isolated_flat_vector_illustration_cartoon_female_characters_taking_individual_lessons_through_messenger_education_digital_technology_concept_74855_100883 {
            get {
                object obj = ResourceManager.GetObject("happy-women-learning-language-online-isolated-flat-vector-illustration-cartoon-fe" +
                        "male-characters-taking-individual-lessons-through-messenger-education-digital-te" +
                        "chnology-concept_74855-100883", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homeiconB {
            get {
                object obj = ResourceManager.GetObject("homeiconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homeiconW {
            get {
                object obj = ResourceManager.GetObject("homeiconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_email_52px {
            get {
                object obj = ResourceManager.GetObject("icons8_email_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_multiply_55px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_multiply_55px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_multiply_55px_2 {
            get {
                object obj = ResourceManager.GetObject("icons8_multiply_55px_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_password_52px_3 {
            get {
                object obj = ResourceManager.GetObject("icons8_password_52px_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_user_52px_3 {
            get {
                object obj = ResourceManager.GetObject("icons8_user_52px_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimizeiconB {
            get {
                object obj = ResourceManager.GetObject("minimizeiconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimizeiconW {
            get {
                object obj = ResourceManager.GetObject("minimizeiconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap moneyiconB {
            get {
                object obj = ResourceManager.GetObject("moneyiconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap moneyiconW {
            get {
                object obj = ResourceManager.GetObject("moneyiconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_year_resolution_plan_for_fresh_graduate_student_free_vector {
            get {
                object obj = ResourceManager.GetObject("new-year-resolution-plan-for-fresh-graduate-student-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_education_52683_6977 {
            get {
                object obj = ResourceManager.GetObject("online-education_52683-6977", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_education_52683_6978 {
            get {
                object obj = ResourceManager.GetObject("online-education_52683-6978", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_education_52683_69781 {
            get {
                object obj = ResourceManager.GetObject("online-education_52683-69781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchiconB {
            get {
                object obj = ResourceManager.GetObject("searchiconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchiconW {
            get {
                object obj = ResourceManager.GetObject("searchiconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingsiconB {
            get {
                object obj = ResourceManager.GetObject("settingsiconB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingsiconW {
            get {
                object obj = ResourceManager.GetObject("settingsiconW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap studenticonB {
            get {
                object obj = ResourceManager.GetObject("studenticonB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap studenticonW {
            get {
                object obj = ResourceManager.GetObject("studenticonW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap succesicon {
            get {
                object obj = ResourceManager.GetObject("succesicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teacher_standing_near_blackboard_holding_stick_isolated_flat_vector_illustration_cartoon_woman_character_near_chalkboard_pointing_alphabet_74855_8600 {
            get {
                object obj = ResourceManager.GetObject("teacher-standing-near-blackboard-holding-stick-isolated-flat-vector-illustration-" +
                        "cartoon-woman-character-near-chalkboard-pointing-alphabet_74855-8600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teachericonB {
            get {
                object obj = ResourceManager.GetObject("teachericonB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teachericonW {
            get {
                object obj = ResourceManager.GetObject("teachericonW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web_development_programmer_engineering_coding_website_augmented_reality_interface_screens_developer_project_engineer_programming_software_application_design_cartoon_illustration_107791_3863 {
            get {
                object obj = ResourceManager.GetObject("web-development-programmer-engineering-coding-website-augmented-reality-interface" +
                        "-screens-developer-project-engineer-programming-software-application-design-cart" +
                        "oon-illustration_107791-3863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web_development_programmer_engineering_coding_website_augmented_reality_interface_screens_developer_project_engineer_programming_software_application_design_cartoon_illustration_107791_38631 {
            get {
                object obj = ResourceManager.GetObject("web-development-programmer-engineering-coding-website-augmented-reality-interface" +
                        "-screens-developer-project-engineer-programming-software-application-design-cart" +
                        "oon-illustration_107791-38631", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
